# Generated by Django 4.2.4 on 2023-08-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='medicines',
            field=models.ManyToManyField(to='purchases.medicinestock'),
        ),
    ]
