# Generated by Django 4.2.4 on 2023-08-19 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchase_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='Supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='purchases.supplier', verbose_name='SUPPLIER NAME'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='PAYMENT_STATUS',
            field=models.CharField(choices=[('C', 'Completed'), ('N', 'Not Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='PURCHASE_DATE',
            field=models.DateField(),
        ),
    ]
