# Generated by Django 4.2.4 on 2023-08-19 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_medicinestock_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='Medicine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='purchases.medicine', verbose_name='MEDICINE NAME'),
            preserve_default=False,
        ),
    ]
