# Generated by Django 4.2.4 on 2023-08-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_supplier_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinestock',
            name='EXPIRY_DATE',
            field=models.DateField(),
        ),
    ]
