# Generated by Django 4.2.4 on 2023-08-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchase_supplier_alter_purchase_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='SUPPLIER_NAME',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='EMAIL',
            field=models.EmailField(max_length=254),
        ),
    ]
